language: python
python:
  - "2.7"
  - "3.4"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install python-coveralls
# command to run tests
script:
  - coverage run --parallel-mode -m unittest discover -s q2c  
  - python setup.py install
  - q2c --help
  - coverage run --parallel-mode -m q2c.command_line -c example/config.json example
  - test -e example/CMakeLists.txt
after_success: 
  - coverage combine
  - coverage report
  - coveralls
