language: python
python:
  - "2.7"
  - "3.4"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coverage
# command to run tests
script:
  - coverage run -m unittest discover -s q2c
after_success: coverage report
